import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import type { SectionCategory, SelectedSections } from "@/types/section";
import { getSection } from "@/data/sectionLibrary";
import { getPreviewComponent } from "./previewMap";

// Export the composed LP as a single React/Tailwind component (.tsx) for
// engineer hand-off. Best-effort HTML→JSX conversion (class→className, style
// strings→objects, void self-close, common SVG attrs). The output is a
// starting point — review before shipping.

// hyphenated / special HTML+SVG attributes → JSX camelCase
const ATTR_MAP: Record<string, string> = {
  class: "className",
  for: "htmlFor",
  tabindex: "tabIndex",
  colspan: "colSpan",
  rowspan: "rowSpan",
  maxlength: "maxLength",
  autocomplete: "autoComplete",
  crossorigin: "crossOrigin",
  srcset: "srcSet",
  "stroke-width": "strokeWidth",
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-dasharray": "strokeDasharray",
  "stroke-miterlimit": "strokeMiterlimit",
  "stroke-opacity": "strokeOpacity",
  "fill-rule": "fillRule",
  "fill-opacity": "fillOpacity",
  "clip-rule": "clipRule",
  "clip-path": "clipPath",
  "stop-color": "stopColor",
  "stop-opacity": "stopOpacity",
  "text-anchor": "textAnchor",
  "dominant-baseline": "dominantBaseline",
  "font-size": "fontSize",
  "font-family": "fontFamily",
  "font-weight": "fontWeight",
  "letter-spacing": "letterSpacing",
  "flood-color": "floodColor",
  "flood-opacity": "floodOpacity",
};

const VOID_TAGS =
  "img|br|hr|input|meta|link|source|area|base|col|embed|param|track|wbr";

function camelStyleKey(k: string): string {
  const key = k.trim();
  if (key.startsWith("--")) return `"${key}"`; // CSS variable
  return key.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function styleToObject(style: string): string {
  const props = style
    .split(";")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((decl) => {
      const i = decl.indexOf(":");
      if (i === -1) return "";
      const key = camelStyleKey(decl.slice(0, i));
      const val = decl.slice(i + 1).trim().replace(/'/g, "\\'");
      return `${key}: '${val}'`;
    })
    .filter(Boolean);
  return `{{ ${props.join(", ")} }}`;
}

function htmlToJsx(html: string): string {
  let out = html;

  // style="..." → style={{ ... }}
  out = out.replace(/style="([^"]*)"/g, (_, s) => `style=${styleToObject(s)}`);

  // rename attributes (longest keys first to avoid partial hits)
  for (const [from, to] of Object.entries(ATTR_MAP).sort(
    (a, b) => b[0].length - a[0].length,
  )) {
    out = out.replace(new RegExp(`(\\s)${from}=`, "g"), `$1${to}=`);
  }

  // self-close void elements
  out = out.replace(
    new RegExp(`<(${VOID_TAGS})\\b([^>]*?)\\s*/?>`, "g"),
    (_, tag, attrs) => `<${tag}${attrs} />`,
  );

  return out;
}

export function buildLpReact(
  ordered: SectionCategory[],
  selected: SelectedSections,
  origin: string,
): string {
  const body = ordered
    .map((cat) => {
      const section = getSection(cat.id, selected[cat.id]);
      if (!section) return "";
      const Preview = getPreviewComponent(section.componentType);
      if (!Preview) return "";
      const markup = renderToStaticMarkup(
        createElement(Preview, { variant: "full" }),
      );
      return `      {/* ${section.componentType} — ${cat.label} */}\n${indent(htmlToJsx(markup), 6)}`;
    })
    .filter(Boolean)
    .join("\n\n");

  const cleanOrigin = origin.replace(/\/$/, "");
  const absolutized = body.replace(
    /(src|href)="\/(?!\/)/g,
    `$1="${cleanOrigin}/`,
  );

  return `// Auto-generated by LP Builder Library.
// Composed landing page as a single React + Tailwind component.
// NOTE: best-effort HTML→JSX conversion — review before shipping.
// Requires Tailwind CSS configured in your project.

export default function GeneratedLP() {
  return (
    <div>
${absolutized}
    </div>
  );
}
`;
}

function indent(s: string, n: number): string {
  const pad = " ".repeat(n);
  return s
    .split("\n")
    .map((line) => (line ? pad + line : line))
    .join("\n");
}
