import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import type { SectionCategory, SelectedSections } from "@/types/section";
import { getSection } from "@/data/sectionLibrary";
import { getPreviewComponent } from "./previewMap";

// 生成LP（選択セクションをカテゴリ順に連結）を「単体で開けるコード」として書き出す。
// - HTML: Tailwind(Play CDN) + 自前テーマトークン + 各セクションの静的HTML
// - 画像は site の絶対URLに張り替えるので、サイト公開中はそのまま表示される

// tailwind.config.ts の extend をエクスポート用に再現（CDN Tailwind に流し込む）
const TAILWIND_CONFIG = `
tailwind.config = {
  theme: {
    extend: {
      fontFamily: {
        sans: ["sofia-pro","Helvetica Neue","Arial","Hiragino Kaku Gothic ProN","Hiragino Sans","Meiryo","sans-serif"],
        lato: ["var(--font-lato)","Helvetica Neue","Arial","sans-serif"],
      },
      colors: {
        canvas: "#f6f7f9", ink: "#1a1a1a", subtle: "#6b7280",
        accent: { DEFAULT: "#004e98", soft: "#e9f0f8", ring: "#3b7cc4", ink: "#003a71" },
        brand: { red: "#bf000b", redmark: "#d70c18" }, muted: "#f8f8f8",
        sansan: { 50:"#eef4fb",100:"#d9e6f4",200:"#b3cce8",300:"#7da9d6",400:"#4080bf",500:"#1a5fa3",600:"#004e98",700:"#003f7d",800:"#003163",900:"#00264d" },
      },
      boxShadow: {
        soft: "0 2px 8px rgba(0,57,113,0.06)",
        card: "8px 8px 30px rgba(0,57,113,0.10)",
        cardhover: "8px 8px 36px rgba(0,57,113,0.16)",
      },
      borderRadius: { lg:"0.375rem", xl:"0.5rem", "2xl":"0.625rem", "3xl":"0.875rem" },
    },
  },
};`;

function orderedSelected(
  categories: SectionCategory[],
  selected: SelectedSections,
) {
  return categories
    .filter((c) => selected[c.id])
    .map((cat) => ({ cat, section: getSection(cat.id, selected[cat.id]) }))
    .filter((x) => x.section);
}

/** 生成LPを単体HTML文字列にする。origin は画像を絶対URL化するためのサイトオリジン。 */
export function buildLpHtml(
  categories: SectionCategory[],
  selected: SelectedSections,
  origin: string,
): string {
  const items = orderedSelected(categories, selected);

  const body = items
    .map(({ section }) => {
      const Preview = getPreviewComponent(section!.componentType);
      if (!Preview) return "";
      const markup = renderToStaticMarkup(
        createElement(Preview, { variant: "full" }),
      );
      return `<!-- ${section!.componentType} -->\n${markup}`;
    })
    .join("\n\n");

  // 相対パスの画像/参照を絶対URLへ（公開中サイトの素材を読み込む）
  const cleanOrigin = origin.replace(/\/$/, "");
  const absolutized = body.replace(/(src|href)="\/(?!\/)/g, `$1="${cleanOrigin}/`);

  return `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Generated Landing Page</title>
<script src="https://cdn.tailwindcss.com"></script>
<script>${TAILWIND_CONFIG}</script>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap" rel="stylesheet" />
<style>
  :root { --font-lato: 'Lato','Helvetica Neue',Arial,sans-serif; }
  html, body { background:#ffffff; color:#1a1a1a; -webkit-font-smoothing:antialiased; }
  body { font-family:"Helvetica Neue",Arial,"Hiragino Kaku Gothic ProN","Hiragino Sans",Meiryo,sans-serif; letter-spacing:0.01em; margin:0; }
</style>
</head>
<body>
${absolutized}
</body>
</html>
`;
}

/** 生成LPの構成を Markdown にする。 */
export function buildLpMarkdown(
  categories: SectionCategory[],
  selected: SelectedSections,
): string {
  const items = orderedSelected(categories, selected);

  const rows = items
    .map(
      ({ cat, section }, i) =>
        `| ${i + 1} | ${cat.label}（${cat.labelJa}） | ${section!.title} | \`${section!.componentType}\` |`,
    )
    .join("\n");

  const details = items
    .map(({ cat, section }, i) => {
      const tags = section!.tags?.length ? section!.tags.join(", ") : "—";
      return `### ${i + 1}. ${cat.label} — ${section!.title}
- componentType: \`${section!.componentType}\`
- 説明: ${section!.description}
- タグ: ${tags}`;
    })
    .join("\n\n");

  return `# Generated Landing Page

選択したセクションをカテゴリ順（category.order）に連結した1本のLP構成です。

## 構成一覧

| # | カテゴリ | セクション | コンポーネント |
|---|---|---|---|
${rows}

## セクション詳細

${details}

---
_Generated by LP Builder Library_
`;
}

/** テキストをファイルとしてダウンロードさせる。 */
export function downloadTextFile(
  filename: string,
  text: string,
  mime = "text/plain;charset=utf-8",
): void {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
